version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: profitFill-postgres-local
    environment:
      POSTGRES_USER: profitFill
      POSTGRES_PASSWORD: profitFill
      POSTGRES_DB: profitFill
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
